import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import { headers } from 'next/headers';
import MoPage from '@/app/(mo)/MoPage';
import PcPage from '@/app/(pc)/PcPage';
import { getHotelList } from './lib/fetch/getHotelList';
import { isMobileDevice } from './lib/isMobileDevice';

const notoSans = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({}: Readonly<{
  children: React.ReactNode;
}>) => {
  const hotelList = await getHotelList();

  const headersList = await headers();
  const userAgent = headersList.get('user-agent') || ''; // 'user-agent' 헤더 값을 가져옴

  console.log(hotelList);

  return (
    <html lang="ko">
      <body className={notoSans.className}>
        {isMobileDevice(userAgent) ? (
          <MoPage hotelList={hotelList} />
        ) : (
          <PcPage hotelList={hotelList} />
        )}
      </body>
    </html>
  );
};

export default RootLayout;
